name: Android CI - Release

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      # 3. Make Gradle executable
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 4. Build Release APK with verbose logs
      - name: Build Release APK (verbose)
        run: ./gradlew clean assembleRelease --info --stacktrace

      # 5. Show APK output paths
      - name: Show APK paths
        run: |
          echo "Listing APK files..."
          find app/build/outputs -type f -name "*.apk"

      # 6. Upload the Release APK
      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: app/build/outputs/apk/free/release/*.apk
